---
- name: Home Server docker host setup
  ansible.builtin.include_tasks: "{{ task }}"
  loop:
    - packages.yml
    - logging.yml
    - storage.yml
    - network.yml
    - gitops.yml
  loop_control:
    loop_var: task
