services:
  romm:
    container_name: romm
    image: rommapp/romm:4.8.1
    restart: unless-stopped
    env_file: secrets.enc.env
    environment:
      - DB_HOST=romm_mariadb
      - DB_NAME=romm
      - DB_USER=romm-user
      - LAUNCHBOX_API_ENABLED=true
      - HASHEOUS_API_ENABLED=true
      - HLTB_API_ENABLED=true
    volumes:
      - /home/diego/services_data/games/romm/resources:/romm/resources
      - /home/diego/services_data/games/romm/redis:/redis-data
      - /media/hd2/data/media/games:/romm/library
      - /home/diego/services_data/games/romm/assets:/romm/assets
      - /home/diego/services_data/games/romm/config:/romm/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.romm.rule=Host(`romm.local.dynabase.nl`)"
      - "traefik.http.routers.romm.entrypoints=https"
      - "traefik.http.routers.romm.tls=true"
      - "traefik.http.services.romm.loadbalancer.server.port=8080"
    depends_on:
      romm_mariadb:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 90s

  romm_mariadb:
    container_name: romm_mariadb
    image: mariadb:12.2.2
    restart: unless-stopped
    env_file: secrets.enc.env
    environment:
      - MARIADB_DATABASE=romm
      - MARIADB_USER=romm-user
    volumes:
      - /home/diego/services_data/games/romm/mysql:/var/lib/mysql
    healthcheck:
      test: [CMD, healthcheck.sh, --connect, --innodb_initialized]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    external: true
    name: home_server_network
