services:

  mattermost:
    container_name: mattermost
    image: mattermost/mattermost-team-edition:11.7.2
    restart: unless-stopped
    env_file: secrets.enc.env
    environment:
      - TZ=Europe/Amsterdam
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SERVICESETTINGS_SITEURL=https://mattermost.dynabase.nl
      - MM_BLEVESETTINGS_INDEXDIR=/mattermost/bleve-indexes
      - MM_EMAILSETTINGS_SENDPUSHNOTIFICATIONS=true
      - MM_EMAILSETTINGS_PUSHNOTIFICATIONSERVER=https://push-test.mattermost.com
      - MM_EMAILSETTINGS_PUSHNOTIFICATIONCONTENTS=full
      - MM_EMAILSETTINGS_SENDEMAILNOTIFICATIONS=true
      - MM_EMAILSETTINGS_ENABLESMTPAUTH=true
      - MM_EMAILSETTINGS_SMTPSERVER=smtp.gmail.com
      - MM_EMAILSETTINGS_SMTPPORT=587
      - MM_EMAILSETTINGS_CONNECTIONSECURITY=STARTTLS
      - MM_EMAILSETTINGS_SMTPUSERNAME=diegojonathanheer@gmail.com
      - MM_EMAILSETTINGS_FEEDBACKNAME=Mattermost
      - MM_EMAILSETTINGS_FEEDBACKEMAIL=diegojonathanheer@gmail.com
      - MM_EMAILSETTINGS_REPLYTOADDRESS=diegojonathanheer@gmail.com
    volumes:
      - /home/diego/services_data/collaboration/mattermost/config:/mattermost/config
      - /home/diego/services_data/collaboration/mattermost/data:/mattermost/data
      - /home/diego/services_data/collaboration/mattermost/logs:/mattermost/logs
      - /home/diego/services_data/collaboration/mattermost/plugins:/mattermost/plugins
      - /home/diego/services_data/collaboration/mattermost/client_plugins:/mattermost/client/plugins
      - /home/diego/services_data/collaboration/mattermost/bleve_indexes:/mattermost/bleve-indexes
    depends_on:
      mattermost_postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 2G
    healthcheck:
      test: ["CMD", "/mattermost/bin/mmctl", "system", "status", "--local"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mattermost_postgres:
    container_name: mattermost_postgres
    image: postgres:16.14-alpine
    restart: unless-stopped
    env_file: secrets.enc.env
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_DB=mattermost
    volumes:
      - /home/diego/services_data/collaboration/mattermost_postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mmuser -d mattermost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  default:
    external: true
    name: home_server_network
