services:
  filebrowser:
    container_name: filebrowser
    image: gtstef/filebrowser:1.2.4-stable
    restart: unless-stopped
    environment:
      TZ: "Europe/Amsterdam"
      FILEBROWSER_CONFIG: "data/config.yaml"
    volumes:
      - /media/hd1:/hd1
      - /media/hd2:/hd2
      - /media/hd3:/hd3
      - /home/diego:/user_home
      - /home/diego/services_data/storage/filebrowser/data:/home/filebrowser/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.local.dynabase.nl`)"
      - "traefik.http.routers.filebrowser.entrypoints=https"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
    deploy:
      resources:
        limits:
          memory: 200M
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nextcloud:
    image: linuxserver/nextcloud:33.0.2
    container_name: nextcloud
    restart: unless-stopped
    env_file: secrets.enc.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=nextcloud
      - MYSQL_HOST=nextcloud_mariadb
    volumes:
      - /home/diego/services_data/storage/nextcloud/config:/config
      - /home/diego/services_data/storage/nextcloud/themes:/themes
      - /media/hd1/nextcloud:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.local.dynabase.nl`)"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
    depends_on:
      nextcloud_mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  nextcloud_mariadb:
    image: mariadb:12.2.2
    container_name: nextcloud_mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    env_file: secrets.enc.env
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - TZ=Europe/Amsterdam
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=nextcloud
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  rustfs:
    container_name: rustfs
    image: rustfs/rustfs:1.0.0-alpha.94
    restart: unless-stopped
    env_file: secrets.enc.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rustfs-api.rule=Host(`rustfs.local.dynabase.nl`)"
      - "traefik.http.routers.rustfs-api.entrypoints=https"
      - "traefik.http.routers.rustfs-api.tls=true"
      - "traefik.http.routers.rustfs-api.service=rustfs-api"
      - "traefik.http.services.rustfs-api.loadbalancer.server.port=9000"
      - "traefik.http.routers.rustfs-console.rule=Host(`rustfs-console.local.dynabase.nl`)"
      - "traefik.http.routers.rustfs-console.entrypoints=https"
      - "traefik.http.routers.rustfs-console.tls=true"
      - "traefik.http.routers.rustfs-console.service=rustfs-console"
      - "traefik.http.services.rustfs-console.loadbalancer.server.port=9001"
    environment:
      - RUSTFS_VOLUMES=/data/rustfs{0..3}
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*
    volumes:
      - /media/hd3/rustfs/data:/data
      - /media/hd3/rustfs/logs:/app/logs
    healthcheck:
      test:
        [
          "CMD",
          "sh", "-c",
          "curl -f http://127.0.0.1:9000/health && curl -f http://127.0.0.1:9001/rustfs/console/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


volumes:
  nextcloud-db:

networks:
  default:
    external: true
    name: home_server_network
