services:

  it-tools:
    container_name: it-tools
    image: corentinth/it-tools:2024.10.22-7ca5933
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.it-tools.rule=Host(`it-tools.local.dynabase.nl`)"
      - "traefik.http.routers.it-tools.entrypoints=https"
      - "traefik.http.routers.it-tools.tls=true"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5

  bentopdf:
    container_name: bentopdf
    image: ghcr.io/alam00000/bentopdf:2.8.6
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bentopdf.rule=Host(`bentopdf.local.dynabase.nl`)"
      - "traefik.http.routers.bentopdf.entrypoints=https"
      - "traefik.http.routers.bentopdf.tls=true"
      - "traefik.http.services.bentopdf.loadbalancer.server.port=8080"
    healthcheck:
      test: wget --spider http://localhost:8080 > /dev/null 2>&1 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  grist:
    container_name: grist
    image: gristlabs/grist:1.7.16
    restart: unless-stopped
    env_file: secrets.enc.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grist.rule=Host(`grist.local.dynabase.nl`)"
      - "traefik.http.routers.grist.entrypoints=https"
      - "traefik.http.routers.grist.tls=true"
      - "traefik.http.services.grist.loadbalancer.server.port=9999"
    environment:
      - PORT=9999
    volumes:
      - /home/diego/services_data/tools/grist/persist:/persist
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/status"]
      interval: 30s
      retries: 3
      timeout: 5s
      start_period: 10s
      start_interval: 5s

  docuseal:
    container_name: docuseal
    image: docuseal/docuseal:2.5.3
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docuseal.rule=Host(`docuseal.local.dynabase.nl`)"
      - "traefik.http.routers.docuseal.entrypoints=https"
      - "traefik.http.routers.docuseal.tls=true"
      - "traefik.http.services.docuseal.loadbalancer.server.port=3000"
    volumes:
      - /home/diego/services_data/tools/docuseal:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  changedetection:
    container_name: changedetection
    image: ghcr.io/dgtlmoon/changedetection.io:0.55.8
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.changedetection.rule=Host(`changedetection.local.dynabase.nl`)"
      - "traefik.http.routers.changedetection.entrypoints=https"
      - "traefik.http.routers.changedetection.tls=true"
      - "traefik.http.services.changedetection.loadbalancer.server.port=5000"
    volumes:
      - /home/diego/services_data/tools/changedetection:/datastore
    healthcheck:
      test: ["CMD-SHELL", "python3 -c \"import sys, urllib.request; sys.exit(1) if 200 != urllib.request.urlopen('http://localhost:5000/').status else sys.exit(0)\""]  # yamllint disable-line rule:line-length
      interval: 60s
      timeout: 2s
      retries: 5

  tandoor:
    container_name: tandoor
    image: vabene1111/recipes:2.6.13
    restart: unless-stopped
    env_file: secrets.enc.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tandoor.rule=Host(`tandoor.local.dynabase.nl`)"
      - "traefik.http.routers.tandoor.entrypoints=https"
      - "traefik.http.routers.tandoor.tls=true"
      - "traefik.http.services.tandoor.loadbalancer.server.port=80"
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=tandoor_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=djangodb
      - POSTGRES_DB=djangodb
      - ALLOWED_HOSTS=tandoor.local.dynabase.nl,tandoor.dynabase.nl,localhost,127.0.0.1
      - CSRF_TRUSTED_ORIGINS=https://tandoor.local.dynabase.nl,https://tandoor.dynabase.nl
    volumes:
      - /home/diego/services_data/tools/tandoor/staticfiles:/opt/recipes/staticfiles
      - /home/diego/services_data/tools/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      tandoor_postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: wget --spider --no-verbose http://localhost:80/openapi/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  tandoor_postgres:
    container_name: tandoor_postgres
    restart: unless-stopped
    image: postgres:16.14-alpine
    env_file: secrets.enc.env
    volumes:
      - /home/diego/services_data/tools/tandoor/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=djangodb
      - POSTGRES_DB=djangodb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U djangodb -d djangodb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


networks:
  default:
    external: true
    name: home_server_network
