http:
  routers:
    router:
      rule: "Host(`router.local.dynabase.nl`)"
      entryPoints:
        - "https"
      service: router
      tls: {}

    pihole:
      rule: "Host(`pihole.local.dynabase.nl`)"
      entryPoints:
        - "https"
      service: pihole
      tls: {}

    homeassistant:
      rule: "Host(`homeassistant.local.dynabase.nl`)"
      entryPoints:
        - "https"
      service: homeassistant
      tls: {}

    homeassistant-external:
      rule: "Host(`homeassistant.dynabase.nl`)"
      entryPoints:
        - "https"
      service: homeassistant
      tls: {}

    proxmox:
      rule: "Host(`proxmox.local.dynabase.nl`)"
      entryPoints:
        - "https"
      service: proxmox
      tls: {}

  services:
    router:
      loadBalancer:
        servers:
          - url: "https://192.168.1.1:443"

    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.1.11:7088"

    homeassistant:
      loadBalancer:
        servers:
          - url: "http://192.168.1.10:8123"

    proxmox:
      loadBalancer:
        servers:
          - url: "https://192.168.1.100:8006"
