services:
  beszel:
    container_name: beszel
    image: henrygd/beszel:0.18.7
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /home/diego/services_data/monitoring/beszel:/beszel_data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.rule=Host(`beszel.local.dynabase.nl`)"
      - "traefik.http.routers.beszel.entrypoints=https"
      - "traefik.http.routers.beszel.tls=true"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"
    healthcheck:
      test: ["CMD", "/beszel", "health", "--url", "http://localhost:8090"]
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 5s

  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:0.18.7
    restart: unless-stopped
    network_mode: host
    env_file: secrets.enc.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /media/hd1/.beszel:/extra-filesystems/sdb1:ro
      - /media/hd2/.beszel:/extra-filesystems/sdd1:ro
      - /media/hd3/.beszel:/extra-filesystems/sde1:ro
      - /home/diego/services_data/monitoring/beszel/agent_data:/var/lib/beszel-agent
    environment:
      LISTEN: 45876
      HUB_URL: https://beszel.dynabase.nl
    healthcheck:
      test: ["CMD", "/agent", "health"]
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 15s
    depends_on:
      beszel:
        condition: service_healthy

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v10.6.1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/diego/services_data/monitoring/dozzle:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.local.dynabase.nl`)"
      - "traefik.http.routers.dozzle.entrypoints=https"
      - "traefik.http.routers.dozzle.tls=true"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s

  portracker:
    container_name: portracker
    image: mostafawahied/portracker:1.3.10
    restart: unless-stopped
    pid: "host"
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - /home/diego/services_data/monitoring/portracker/data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portracker.rule=Host(`portracker.local.dynabase.nl`)"
      - "traefik.http.routers.portracker.entrypoints=https"
      - "traefik.http.routers.portracker.tls=true"
      - "traefik.http.services.portracker.loadbalancer.server.port=4999"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4999/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  uptime-kuma:
    image: louislam/uptime-kuma:2.3.2
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - /home/diego/services_data/monitoring/uptime-kuma/data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma.local.dynabase.nl`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=https"
      - "traefik.http.routers.uptime-kuma.tls=true"
      - "traefik.http.routers.uptime-kuma.tls.certresolver=le"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
    environment:
      - TZ=Europe/Amsterdam
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


networks:
  default:
    external: true
    name: home_server_network
